# Auto-labeling configuration for PRs
# See: https://github.com/actions/labeler

'area: kernel':
  - changed-files:
      - any-glob-to-any-file:
          - src/kernel/**/*
          - include/kernel.h

'area: memory':
  - changed-files:
      - any-glob-to-any-file:
          - src/mm/**/*
          - include/memory.h
          - include/pmm.h
          - include/vmm.h

'area: filesystem':
  - changed-files:
      - any-glob-to-any-file:
          - src/fs/**/*
          - include/fs/**/*

'area: networking':
  - changed-files:
      - any-glob-to-any-file:
          - src/net/**/*
          - include/net/**/*

'area: drivers':
  - changed-files:
      - any-glob-to-any-file:
          - src/dev/**/*
          - include/dev/**/*

'area: crypto':
  - changed-files:
      - any-glob-to-any-file:
          - src/crypto/**/*
          - include/crypto/**/*

'area: build':
  - changed-files:
      - any-glob-to-any-file:
          - Makefile
          - linker.ld
          - scripts/**/*
          - .github/workflows/**/*

'area: documentation':
  - changed-files:
      - any-glob-to-any-file:
          - README.md
          - '*.md'
          - docs/**/*

'dependencies':
  - changed-files:
      - any-glob-to-any-file:
          - '**/package*.json'
          - '**/requirements*.txt'
          - '**/Makefile'
